# Test Database
version: '3.2'
services:
  database:
    container_name: db
    build: database
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "notifications"
