version: '3'

services:
  subscriber:
    build: subscriber
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
    links:
      - database
  fake-twitch-websub:
    build: fake-twitch-websub
    ports:
      - 3001:3001
  database:
    build: database
