version: '3'

services:
  subscriber:
    build: subscriber
    ports:
      - "3000:3000"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "notifications"
  fake-twitch-websub:
    build: fake-twitch-websub
    ports:
      - "3001:3001"
  database:
    build: database
    ports:
      - "3307:3306"
    expose:
      - "3306"
