# e2e
version: "3.2"
services:
  subscriber:
    container_name: sub
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - HUB_CALLBACK=${hub_callback_env}
      - HUB_URL=${hub_url_env}
  database:
    container_name: db
    build: database
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "notifications"
