# e2e
version: '3.2'
services:
  subscriber:
    container_name: sub
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on: 
      - database
    environment:
      - HUB_CALLBACK=http://localhost:3000/approval-callback
      - HUB_URL=http://host.docker.internal:3001/hub
  database:
    container_name: db
    build: database
    ports:
      - "3307:3306"
    expose:
      - "3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "notifications"
